# python中的数据结构
由于python是动态类型的语言，所以每一个对象都会包含许多附加的属性，来实现动态。

自然地，python自带的列表也是可以存储多种类型的数据。

这就导致，当python自带的列表存储单一类型的数据时，会产生大量的附加属性，浪费存储空间。

而numpy的数组类型就是为了解决这一问题而提出的。


# numpy创建数组
## 1. 从python列表中创建数组

In [1]:
import numpy as np

In [4]:
# 整数数组
np.array([1,3,4,2,])

array([1, 3, 4, 2])

In [5]:
# 当数据类型不统一时，会自动向上转型
np.array([1,3,2,1.1])

array([1. , 3. , 2. , 1.1])

In [6]:
# 可以使用指定的数据类型
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

## 2. 从头创建数组

In [7]:
# 创建全零数组
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# 创建全1数组
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# 创建相同数据数组
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
# 创建递增数组
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# 创建线段等分点，0到1，5等分
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# 创建随机矩阵，0-1之间的随机数
np.random.random((3,3))

array([[0.78566974, 0.33399316, 0.47696188],
       [0.08477035, 0.10908105, 0.927212  ],
       [0.55354303, 0.78595354, 0.16300252]])

In [14]:
# 创建随机矩阵，服从正态分布，均值为0方差为1
np.random.normal(0,1,(3,3))

array([[ 0.60954628,  0.62000072, -2.09491443],
       [ 0.82742071, -0.93096834,  2.06662444],
       [ 0.81506007,  0.2944726 ,  0.99583064]])

In [15]:
# 创建随机矩阵，区间内随机整型
np.random.randint(0,10,(3,3))

array([[7, 8, 4],
       [5, 6, 5],
       [5, 3, 2]])

In [16]:
# 创建单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# 创建空矩阵，其中的数据由内存内随机选择的数据进行填充
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])