# 1. 数组的属性

数组属性包括数组的维度、形状、总大小、数据类型等一系列属性。

In [1]:
import numpy as np

In [5]:
# 设置随机数种子，保证随机结果相同
np.random.seed(0)
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [7]:
x = np.random.random((3,4,5))
# 数组的维度
print("dim:",x.ndim)
# 数组的形状
print("shape:",x.shape)
# 数组的总大小
print("dim:",x.size)
# 数组的数据类型
print("dtype:",x.dtype)

dim: 3
shape: (3, 4, 5)
dim: 60
dtype: float64


# 2. 数组的索引

# 3. 数组的切分

# 4. 数组的变形

可以使用reshape直接变形，也可以使用newaxis通过添加维度的方式进行变形

In [14]:
# 使用reshape直接变形
x = np.array([1,2,3])
# 行向量
print(x.reshape((1,3)))
# 列向量
print(x.reshape((3,1)))

[[1 2 3]]
[[1]
 [2]
 [3]]


In [15]:
# 使用添加维度的方式进行变换
# 行向量
print(x[np.newaxis,:])
# 列向量
print(x[:,np.newaxis])

[[1 2 3]]
[[1]
 [2]
 [3]]


# 5. 数组的拼接和分裂

数组拼接可以使用concatenate进行拼接，也可以使用hstack和vstack进行垂直和水平方向的拼接

In [17]:
# 通用方法，np.concatenate
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [19]:
# 二维数组拼接
grid = np.array([[1,2,3],[4,5,6]])
# 第一轴拼接
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [20]:
# 第二轴拼接
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [21]:
# 还可以使用vstack和hstack来进行拼接
# 垂直拼接
np.vstack([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [22]:
# 水平拼接
np.hstack([grid,grid])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

和拼接一样的，分裂也可以有两种方式进行实现。

使用通用的方法split，或者指定垂直水平的方法hsplit、vsplit

In [23]:
x = [1,2,3,99,99,3,2,1]
# 传入切分点，即在3和5处各切一刀
x1, x2, x3 = np.split(x,[3,5])
x1,x2,x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [27]:
# 垂直切割
lower, upper = np.vsplit(grid,[1])
lower, upper

(array([[1, 2, 3]]), array([[4, 5, 6]]))

In [28]:
# 水平切割
left, right = np.hsplit(grid,[1])
left, right

(array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]]))