# 1. 通用函数

与 python 自带计算中循环数组进行计算不同，numpy 使用了向量的形式进行计算，大大加快了计算速度。

numpy 从底层便一直调用通用函数进行计算。


In [2]:
import numpy as np


# 2. numpy 算数运算符与对应的通用函数

| 运算符 | 对应的通用函数  | 描述     |
| ------ | --------------- | -------- |
| +      | np.add          | 加法运算 |
| -      | np.subtract     | 减法运算 |
| -      | np.negative     | 负数运算 |
| \*     | np.multiply     | 乘法运算 |
| /      | np.divide       | 除法运算 |
| //     | np.floor_divide | 整除运算 |
| \*\*   | np.power        | 指数运算 |
| %      | np.mod          | 取余运算 |

其他常用运算如下：


In [3]:
# 绝对值
x = np.array([-2, -1, 0, 1, 2])
# 两个函数相同
np.absolute(x), np.abs(x)


(array([2, 1, 0, 1, 2]), array([2, 1, 0, 1, 2]))

In [6]:
# 三角函数
theta = np.linspace(0, np.pi, 3)
print("theta: ", theta)
print("sin(theta): ", np.sin(theta))
print("cos(theta): ", np.cos(theta))
print("tan(theta): ", np.tan(theta))
x = [-1, 0, 1]
print("arcsin(x): ", np.arcsin(x))
print("arccos(x): ", np.arccos(x))
print("arctan(x): ", np.arctan(x))


theta:  [0.         1.57079633 3.14159265]
sin(theta):  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta):  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta):  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin(x):  [-1.57079633  0.          1.57079633]
arccos(x):  [3.14159265 1.57079633 0.        ]
arctan(x):  [-0.78539816  0.          0.78539816]


In [9]:
# 指数和对数
x = [1, 2, 3]
print("x = ", x)
# 指数
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3, x))
# 对数
print("ln(x) = ", np.log(x))
print("log2(x) = ", np.log2(x))
print("log10(x) = ", np.log10(x))


x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]
ln(x) =  [0.         0.69314718 1.09861229]
log2(x) =  [0.        1.        1.5849625]
log10(x) =  [0.         0.30103    0.47712125]


In [10]:
# 高级通用函数包
from scipy import special


# 3. 高级的通用函数特性

### 1. 指定输出

可以通过指定 out 参数来指定计算结果的存放位置


In [11]:
# 指定存放变量
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
y


array([ 0., 10., 20., 30., 40.])

In [13]:
# 指定存放切片
y = np.zeros(10)
np.power(2, x, out=y[::2])
y


array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

### 2. 聚合

numpy 中提供了许多聚合函数，可以直接通过链式调用来配合其他通用函数进行使用


In [18]:
# reduce对当前数组进行计算
x = np.arange(1, 6)
# 计算数组中元素和
print(np.add.reduce(x))
# 就散数组中元素乘积
print(np.multiply.reduce(x))


15
120


In [19]:
# accumulate 存储中间结果
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))


[ 1  3  6 10 15]
[  1   2   6  24 120]


### 3. 外积

可以通过在结尾添加 outer 方法的方式，来获取两个输入数组中所有元素对的计算结果


In [20]:
# 打印乘法表
np.multiply.outer(x, x)


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

# 4. 聚合函数


In [ ]:
# 使用sum函数实现数组值求和
L = np.random.random(100)
# 两种调用方式均可
np.sum(L), L.sum()

(48.234099239172984, 48.234099239172984)

In [ ]:
# 最大值和最小值
L.max(), np.max(L), L.min(), np.min(L)

(0.9961327715272777,
 0.9961327715272777,
 0.008787223367416663,
 0.008787223367416663)

In [ ]:
# 多维度聚合
M = np.random.random((3, 4))
# 所有元素相加
M.sum()


6.273903186483039

In [ ]:
# 指定坐标轴计算
M.min(axis=0), M.max(axis=1)


(array([0.13345553, 0.41405496, 0.24505196, 0.19362933]),
 array([0.90304763, 0.96318465, 0.73330971]))

其他常用聚合函数
| 函数名称 | NaN 安全版本 | 描述 |
| ---- | ---- | ---- |
| np.sum | np.nansum | 计算元素的和 |
| np.prod | np.nanprod | 计算元素的积 |
| np.mean | np.nanmean | 计算元素的平均值 |
| np.std | np.nanstd | 计算元素的标准差 |
| np.var | np.nanvar | 计算元素的方差 |
| np.min | np.nanmin | 找出最小值 |
| np.max | np.nanmax | 找出最大值 |
| np.argmin | np.nanargmin | 找出最小值的索引 |
| np.argmax | np.nanargmax | 找出最大值的索引 |
| np.median | np.nanmedian | 计算元素的中位数 |
| np.percentile | np.nanpercentile | 计算基于元素排序的统计值 |
| np.any | N/A | 验证任何一个元素是否为真 |
| np.all | N/A | 验证所有元素是否为真 |


# 5. 比较、掩码和布尔逻辑

### 1. 比较操作


In [5]:
# 比较操作
x = np.array([1, 2, 3, 4, 5])
x < 3, x > 3, x <= 3, x >= 3, x != 3, x == 3


(array([ True,  True, False, False, False]),
 array([False, False, False,  True,  True]),
 array([ True,  True,  True, False, False]),
 array([False, False,  True,  True,  True]),
 array([ True,  True, False,  True,  True]),
 array([False, False,  True, False, False]))

### 2. 布尔值及其运算


In [11]:
# 由于False存储为0，True存储为1，所以我们有以下几个方式来统计True的个数
x = np.random.randint(0, 5, (3, 4))
print(x)
np.count_nonzero(x < 3), np.sum(x < 3)


[[3 2 0 4]
 [4 4 1 3]
 [0 3 2 4]]


(5, 5)

In [13]:
# 可以指定坐标轴进行计算
np.sum(x < 3, axis=1), np.sum(x < 3, axis=0)


(array([2, 1, 2]), array([1, 1, 3, 0]))

In [16]:
# 可以使用any()和all()快速检查
# 有没有超过4的
print(np.any(x > 4))
# 有没有小于1的
print(np.any(x < 1))
# 是否所有值都小于5
print(np.all(x < 5))
# 是否所有值都等于3
print(np.all(x == 3))


False
True
True
False


### 3. 逻辑运算

& 与 ， | 或 ， ^ 异或 ， ~ 非


In [17]:
# 筛选大于1小于4的元素
np.sum((x > 1) & (x < 4))


5

### 4. 将布尔数组作为掩码


In [18]:
# 直接选出
x[x < 3]


array([2, 0, 1, 0, 2])