In [1]:
import numpy as np


# 1. 花哨索引

In [10]:
# 以数组作为索引获得一维数组
x = np.random.randint(0, 100, 10)
# 使用数组作为索引获得元素
x[[4, 6, 8]]


array([90, 73, 87])

In [11]:
# 注意查询结果和索引数组的形状一致，而不是被索引数组的形状一直
x[[[4, 7], [6, 3]]]


array([[90, 99],
       [73, 49]])

In [13]:
# 多维数组中的花哨索引
X = np.arange(12).reshape((3, 4))
# 获取（0,1），（1,2），（2,3）三个位置的数据
# 左边list是行，右边list是列
X[[0, 1, 2], [1, 2, 3]]


array([ 1,  6, 11])

# 2. 数组排序

In [22]:
# 使用sort返回排好序的数组
x = np.array([2,1,4,3,5])
np.sort(x)
# 注意使用x.sort()会直接改变x数组本身，而不会输出结果

array([1, 2, 3, 4, 5])

In [25]:
# 使用argsort返回排好序的索引
np.argsort(x)

array([1, 0, 3, 2, 4])

In [26]:
# 部分排序
# 降序排序前三个数据
np.partition(x,3)

array([3, 2, 1, 4, 5])